### ISSUE TITLE
Retry Button

### ISSUE THREAD

**Issue by Heavendart888** [VasuGajjar/music_player#1]
Bro There is no retry Button Please Implement it.
By The way your Work Is just awesome..

**Comment by VasuGajjar** [comment]
Thank you for the complement 😄
But I am unable to understand for which task/screen you are talking about to add retry button.

**Comment by Heavendart888** [comment]
When I am adding new music to my storage than it is not added to the music player

**Comment by VasuGajjar** [comment]
I have added fixed the problem, you can try the updated build.
Thanks for reporting 😄

**Comment by Heavendart888** [comment]
After performing retry it is not showing any music. please fix it soon.

**Comment by Heavendart888** [comment]
Now showing no music after retry.
Below is the screenshot

**Comment by Heavendart888** [comment]
Bro the problem is only present while in the testing or debug phase in the
emulator basically.
The final apk release is all ok.
